---
title: "Transcript Annotation Database for *Oryza sativa*"
author: "Kabilan S"
date: "2026-08-10"
output: BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{Transcript Annotation Database for Oryza sativa}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Introduction

**TxDb.Osativa.MSU.RGAP7** is a Bioconductor-compatible transcript annotation
package for *Oryza sativa* generated from the official **Rice Genome Annotation
Project (RGAP) Release 7** GFF3 annotation based on the **IRGSP-1.0** reference
genome (also known as MSU7).

The package provides genomic coordinates and transcript models, including genes,
transcripts, exons, coding sequences (CDS), and promoter regions. It is intended
for downstream genomic analyses using Bioconductor packages such as
**GenomicFeatures**, **GenomicRanges**, **Signac**, **ArchR**, and **ChIPseeker**.

The TxDb object itself is not shipped inside the package; it is hosted on
**AnnotationHub** and downloaded on first use.


``` r
# Installation
if (!requireNamespace("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager")
}
BiocManager::install(c(
    "AnnotationHub",
    "GenomicFeatures",
    "GenomicRanges"
))
```

## Loading packages

``` r
library(AnnotationHub)
library(GenomicFeatures)
```


``` r
# Downloading the TxDb file from AnnotationHub
TxDb.Osativa.MSU.RGAP7 <- tryCatch({
    ah <- AnnotationHub()
    ah[["AH122276"]]
}, error = function(e) NULL)
```

```
## snapshotDate(): 2026-04-23
```



# TxDb file summary


``` r
TxDb.Osativa.MSU.RGAP7
```

# Chromosome information


``` r
seqinfo(TxDb.Osativa.MSU.RGAP7)
```

# Available chromosomes


``` r
seqlevels(TxDb.Osativa.MSU.RGAP7)
```
The 12 nuclear chromosomes of the IRGSP‑1.0 / MSU7 assembly. These contain the vast majority of annotated genes. 
`ChrUn` : Unanchored contigs – sequences that could not be placed on any chromosome. Sometimes called “ChrUnknown”.
`ChrSy` : Syngenta pseudomolecule – a separate assembly contributed by Syngenta that contains additional sequence not present in the main IRGSP‑1.0 build. It is often used for the plastid genome or extra scaffolds.

# Gene annotations

Retrieve all annotated genes.


``` r
genes(TxDb.Osativa.MSU.RGAP7)
```

# Transcript annotations


``` r
head(transcripts(TxDb.Osativa.MSU.RGAP7))
```

# Exon annotations


``` r
head(exons(TxDb.Osativa.MSU.RGAP7))
```

# Coding sequence (CDS) annotations


``` r
head(cds(TxDb.Osativa.MSU.RGAP7))
```

# Promoter regions

Extract promoter regions 2 kb upstream and 200 bp downstream of transcription start sites.


``` r
head(promoters(
    TxDb.Osativa.MSU.RGAP7,
    upstream = 2000,
    downstream = 200
))
```

# Transcripts grouped by gene


``` r
tx_by_gene <- GenomicFeatures::transcriptsBy(TxDb.Osativa.MSU.RGAP7, by = "gene")
tx_by_gene
```

# Exons grouped by transcript


``` r
exonsBy(TxDb.Osativa.MSU.RGAP7, by = "tx")
```

# Converting MSU identifiers to RAP-DB identifiers

Gene models in this database are keyed by MSU locus identifiers
(`LOC_Os##g#####`). Many rice resources instead use RAP-DB identifiers
(`Os##g#######`). `msu_to_rap()` translates between the two, preserving input
order and dropping identifiers that cannot be converted.


``` r
msu_ids <- c("LOC_Os01g01010", "LOC_Os01g01019", "LOC_Os01g01040")
rap_ids <- msu_to_rap(msu_ids)
print(rap_ids)
```

```
## [1] "Os01g0100100" "Os01g0100200" "Os01g0100500"
```

# Session information


``` r
sessionInfo()
```

```
## R version 4.6.1 (2026-06-24 ucrt)
## Platform: x86_64-w64-mingw32/x64
## Running under: Windows 11 x64 (build 26200)
## 
## Matrix products: default
##   LAPACK version 3.12.1
## 
## locale:
## [1] LC_COLLATE=English_India.utf8 
## [2] LC_CTYPE=English_India.utf8   
## [3] LC_MONETARY=English_India.utf8
## [4] LC_NUMERIC=C                  
## [5] LC_TIME=English_India.utf8    
## 
## time zone: Asia/Calcutta
## tzcode source: internal
## 
## attached base packages:
## [1] stats4    stats     graphics  grDevices utils    
## [6] datasets  methods   base     
## 
## other attached packages:
##  [1] GenomicFeatures_1.65.0       
##  [2] AnnotationDbi_1.74.0         
##  [3] Biobase_2.73.2               
##  [4] GenomicRanges_1.64.0         
##  [5] Seqinfo_1.2.0                
##  [6] IRanges_2.46.0               
##  [7] S4Vectors_0.50.1             
##  [8] AnnotationHub_4.2.2          
##  [9] BiocFileCache_3.2.0          
## [10] dbplyr_2.6.0                 
## [11] BiocGenerics_0.58.1          
## [12] generics_0.1.4               
## [13] TxDb.Osativa.MSU.RGAP7_0.99.6
## [14] testthat_3.3.2               
## 
## loaded via a namespace (and not attached):
##  [1] tidyselect_1.2.1           
##  [2] dplyr_1.2.1                
##  [3] blob_1.3.0                 
##  [4] filelock_1.0.3             
##  [5] Biostrings_2.80.1          
##  [6] bitops_1.1-0               
##  [7] fastmap_1.2.0              
##  [8] RCurl_1.98-1.19            
##  [9] GenomicAlignments_1.49.1   
## [10] XML_3.99-0.23              
## [11] digest_0.6.39              
## [12] lifecycle_1.0.5            
## [13] riceidconverter_1.1.1      
## [14] ellipsis_0.3.3             
## [15] KEGGREST_1.53.6            
## [16] RSQLite_3.53.3             
## [17] magrittr_2.0.5             
## [18] compiler_4.6.1             
## [19] rlang_1.3.0                
## [20] tools_4.6.1                
## [21] yaml_2.3.12                
## [22] rtracklayer_1.73.0         
## [23] knitr_1.51                 
## [24] S4Arrays_1.13.0            
## [25] bit_4.6.0                  
## [26] pkgbuild_1.4.8             
## [27] curl_7.1.0                 
## [28] DelayedArray_0.38.2        
## [29] pkgload_1.5.3              
## [30] abind_1.4-8                
## [31] BiocParallel_1.47.0        
## [32] rsconnect_1.10.1           
## [33] withr_3.0.3                
## [34] purrr_1.2.2                
## [35] desc_1.4.3                 
## [36] grid_4.6.1                 
## [37] SummarizedExperiment_1.42.0
## [38] cli_3.6.6                  
## [39] rmarkdown_2.31             
## [40] crayon_1.5.3               
## [41] otel_0.2.0                 
## [42] rstudioapi_0.19.0          
## [43] httr_1.4.8                 
## [44] rjson_0.2.23               
## [45] sessioninfo_1.2.4          
## [46] DBI_1.3.0                  
## [47] cachem_1.1.0               
## [48] parallel_4.6.1             
## [49] BiocManager_1.30.27        
## [50] XVector_0.52.0             
## [51] restfulr_0.0.17            
## [52] matrixStats_1.5.0          
## [53] vctrs_0.7.3                
## [54] devtools_2.5.2             
## [55] Matrix_1.7-6               
## [56] bit64_4.8.2                
## [57] glue_1.8.1                 
## [58] codetools_0.2-20           
## [59] BiocVersion_3.23.1         
## [60] BiocIO_1.22.0              
## [61] tibble_3.3.1               
## [62] pillar_1.11.1              
## [63] rappdirs_0.3.4             
## [64] htmltools_0.5.9            
## [65] brio_1.1.5                 
## [66] R6_2.6.1                   
## [67] httr2_1.3.0                
## [68] rprojroot_2.1.1            
## [69] evaluate_1.0.5             
## [70] lattice_0.22-9             
## [71] png_0.1-9                  
## [72] Rsamtools_2.29.0           
## [73] cigarillo_1.3.1            
## [74] memoise_2.0.1              
## [75] SparseArray_1.13.2         
## [76] xfun_0.60                  
## [77] fs_2.1.0                   
## [78] MatrixGenerics_1.24.0      
## [79] usethis_3.2.1              
## [80] pkgconfig_2.0.3
```
